name: vedb_analysis_1.0
channels:
  - anaconda
  - conda-forge
  - auto
  - vedb
dependencies:
  - python==3.8
  - pip
  - black
  - pipreqs
  - numpy
  - matplotlib
  - pandas
  - h5py
  - imageio
  - scipy
  - pyyaml
  - scikit-image
  - scikit-learn
  - pupil_recording_interface # from vedb channel
  - msgpack-python==0.6.2
  - plotly
  - numcodecs
  - cython
  - tqdm
  - pip:
    - pupil-detectors
    - git+https://github.com/cheind/py-thin-plate-spline.git
